### ISSUE TITLE
_mkostemp lazy binding failed when running on OS X 10.11

### ISSUE THREAD

**Issue by apjanke** [octave-app/octave-app-bundler#44]
When I run the 4.4.0 beta 6 pre-test build on an OS X 10.11 VM, I get an error on Octave startup, right after saying "Yes" to the "rebuild the font cache now?" that pops up on initial program startup.

<img width="419" alt="screen shot 2018-07-24 at 4 44 21 am" src="https://user-images.githubusercontent.com/2618447/43127046-773155c8-8efc-11e8-9535-362ad5b6783d.png">

```
dyld: lazy symbol binding failed: Symbol not found: _mkostemp
  Referenced from: /Applications/Octave-4.4.0.app/Contents/Resources/usr/Cellar/fontconfig_2.13.0/2.13.0/lib/libfontconfig.1.dylib (which was built for Mac OS X 10.13)
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _mkostemp
  Referenced from: /Applications/Octave-4.4.0.app/Contents/Resources/usr/Cellar/fontconfig_2.13.0/2.13.0/lib/libfontconfig.1.dylib (which was built for Mac OS X 10.13)
  Expected in: /usr/lib/libSystem.B.dylib
[...]
```

I suspect this is due to the fontconfig package being built for the newer version of OS X.

I don't think there's an easy way to handle this in Homebrew. They don't provide a way of specifying the version of the OS X SDK to link against, since building redistributables (besides bottles) isn't a supported use of Homebrew. For their bottles, they just have a build box that's running the exact OS for each of their target OSes.

I'll fiddle around with the fontconfig formula a bit on this, but the easiest solution is probably just to install an older version of OS X on the Core2 build box when it arrives, and use that for project builds.

**Comment by schoeps** [comment]
Strange that this error suddenly pops up! Or were we just lucky before? 

We could deactivate the applescript that does the resetting of the font cache but I guess this would shift the problem only to the first time that the user call `plot`.

**Comment by apjanke** [comment]
> Or were we just lucky before?

We were just lucky, or lazy. I was only testing the build on macOS 10.13 High Sierra, so the issues with older versions didn't pop up.

**Comment by apjanke** [comment]
Newest version of GCC does not work on OS X 10.9 Mavericks.

```
==> Downloading https://ftp.gnu.org/gnu/gcc/gcc-8.1.0/gcc-8.1.0.tar.xz
######################################################################### 100.0%
==> ../configure --build=x86_64-apple-darwin13.4.0 --prefix=/Applications/Octave
==> make
Last 15 lines from /Users/janke/Library/Logs/Homebrew/gcc_8.1.0/02.make:
/usr/bin/install -c -m 644 libgcov.a ../../.././gcc/i386/
chmod 644 ../../.././gcc/i386/libgcov.a
ranlib ../../.././gcc/i386/libgcov.a
parts="crt3.o crttms.o crttme.o crtprec32.o crtprec64.o crtprec80.o crtfastmath.o";				\
	for file in $parts; do					\
	  rm -f ../../.././gcc/i386/$file;		\
	  /usr/bin/install -c -m 644 $file ../../.././gcc/i386/;	\
	  case $file in 					\
	    *.a)						\
	      ranlib ../../.././gcc/i386/$file ;;	\
	  esac;							\
	done
make[2]: *** [all-stage1-target-libgcc] Error 2
make[1]: *** [stage1-bubble] Error 2
make: *** [all] Error 2

Do not report this issue to Homebrew/brew or Homebrew/core!


Error: You are using macOS 10.9.
We (and Apple) do not provide support for this old version.
You will encounter build failures and other breakages.
Please create pull-requests instead of asking for help on Homebrew's
GitHub, Discourse, Twitter or IRC. As you are running this old version,
you are responsible for resolving any issues you experience.
```

Need to either pull in an older version of GCC, or select a newer minimum version of OS X to support.

**Comment by apjanke** [comment]
Hey Sebastian, we need to decide what the earliest support version of OS X is going to be for our Octave.app builds.

Homebrew's earliest supported Mac version is 10.11 El Capitan. That is a pretty strong reason for choosing 10.11, since we're piggybacking on top of Homebrew for all our package installations.

We could also choose 10.9 Mavericks, since per [here](http://gs.statcounter.com/macos-version-market-share/desktop/worldwide), 10% of Mac users are still on 10.10 Yosemite, and 3% on 10.9 Mavericks. This would take some work, though, since the current GCC is broken on 10.9, and other formulae might be too.

Do you have a sense of how many of your students might still be using older versions of OS X?

**Comment by schoeps** [comment]
I have no numbers but my impression is that macOS users (and students from computational sciences in particular) are early adopters. The supported hardware of El capitan (10.11) goes back to 2007, this is longer than any student should be studying :-) In short: I‘d say 10.11 is fair.

**Comment by apjanke** [comment]
Sounds good. Going with 10.11 El Capitan.

**Comment by apjanke** [comment]
Fixed by building on OS X 10.11 El Capitan in a VM. Tested and it runs now on both 10.11 and 10.13 without that error popping up.

**Comment by schoeps** [comment]
Did you already upload a new test build? I am quite curious :)

**Comment by schoeps** [comment]
Work great on 10.13. I am setting up a virtual machine with Mojave 10.14 to see if that works, too. If yes, I'd say we are ready to go...

**Comment by schoeps** [comment]
Ok! Preliminary test on Mojave are good. Shall we call this a release candidate and do a final announcement on the octave mailing list (and in cc the macOS guys: Carlo, Simone, Ben)?

**Comment by apjanke** [comment]
Sorry, gotta due one more beta to pick up JDK 1.8 u181 (#46); don't want to stick users with an old Java release.

https://github.com/octave-app/octave-app/releases/tag/v4.4.0-beta7

If this one tests out, then yeah, let's call it a release candidate and announce to the list.

I've done basic tests on it; installation is clean and test suite passes on my 10.11 VM and 10.13 box. `pkg install -forge control; pkg load control; bode(ss(-1, 1, 1, 0))` works on both.

**Comment by schoeps** [comment]
Also here, quick tests on 10.13 and 10.14 are fine. On the plain 13.14 one gets a nice dialog asking to install the command line utils. However, Java is not working as I have installed Java 10.0.2.

**Comment by apjanke** [comment]
Okay, sounds good. I've made this one RC1, and I think it's ready for announcement to the list.

https://github.com/octave-app/octave-app/releases/tag/v4.4.0-rc1

**Comment by schoeps** [comment]
Shall I post at the mailig list or do you? I‘d prefer the latter since I am on holidays and I am trying to reduce the time I am spending online :-)

**Comment by apjanke** [comment]
Don't worry; I'll post it. Enjoy your holidays!
